### ISSUE TITLE
TODO project is vulnerable to XSS/HTML injection attacks

### ISSUE THREAD

**Issue by dmdhrumilmistry** [pyscript/pyscript#1405]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

TODO example project is vulnerable to XSS/HTML injection attacks. 

**Payload Used:**

```html
<button onclick='javascript:confirm("vulnerable");document.location.href="https://dmdhrumilmistry.github.io"'>click me</button>
```

**Result:**

![XSS output image](https://user-images.githubusercontent.com/56185972/234077548-f7e52f27-e5b3-495a-814a-d3ffcb3d3a15.png)

**Issue:** Since most of the devs will be learning pyscript referring the examples, they'll be making applications which will be vulnerable to XSS/HTML injection. We would appreciate if pyscript team can also use secure coding techniques while creating examples; this will help devs to build secure applications.

### Additional Context

creating a cheatsheet might help devs to avoid such common issues in their applications

**Comment by WebReflection** [comment]
@dmdhrumilmistry wait a minute ... are you saying that if you add HTML as TODO item content that gets injected as HTML? Not sure that's just intentional / by-design for demo sake, but if that's the case we might avoid tasks as HTML, yes 👍

**Comment by WebReflection** [comment]
@dmdhrumilmistry I've just tested locally and also checked [the file part where we use innerText](https://github.com/pyscript/pyscript/blob/main/examples/todo.py#L33), not `innerHTML` to add the task ... this is what I see so we might need a step-by-step way to reproduce your issue or maybe it was fixed already (a month ago) and it's not live yet.

/cc @antocuni 

![Screenshot from 2023-04-24 20-43-57](https://user-images.githubusercontent.com/85749/234087844-c284be92-294c-4626-aedd-4d79942319e2.png)

**Comment by dmdhrumilmistry** [comment]
using `innerText` would fix the issue! ohh okay. cool. When will it be deployed?

**Comment by FabioRosado** [comment]
I may be wrong since I've been focused on the pyscript.com side of things but I'm assuming that the next release will happen when the work for workers is a bit more stable 🤔

**Comment by dmdhrumilmistry** [comment]
okay cool!

**Comment by fpliger** [comment]
Sorry I missed the thread. 

Yes, next release should be happening within a month timeframe (the big task holding the release is indeed workers, as @FabioRosado mentioned). 

@WebReflection @dmdhrumilmistry am I reading correctly that, given the comments above around `innerText`, we can close this issue?

**Comment by WebReflection** [comment]
@fpliger the label `waiting for release` is there to signal this is not a bug and will be closed once we release. If we close it before that there's no signal the bug is gone because there's no opened issue so we should just ignore these labelled issues and close them once we release.

**Comment by dmdhrumilmistry** [comment]
> Sorry I missed the thread.
> 
> Yes, next release should be happening within a month timeframe (the big task holding the release is indeed workers, as @FabioRosado mentioned).
> 
> @WebReflection @dmdhrumilmistry am I reading correctly that, given the comments above around `innerText`, we can close this issue?

@fpliger, I'll prefer to close this once after releasing the fix. Else team might miss the issue.

**Comment by fpliger** [comment]
@dmdhrumilmistry  👍  

@WebReflection Ok. This is different than the process we were adopting earlier (I probably missed the changes). I guess the rationale here is reflecting the state of the latest released version vs the state of `main`. We are due to sit down and put down a project/contribution workflow and guidelines anyway, so let's make sure we talk through this when we have that conversation

**Comment by WebReflection** [comment]
@fpliger in all fairness it was my initiative and I've asked in the channel if that was OK but I guess I wasn't too loud there.

The (personal) idea was to meet users expectations, see:

> I'll prefer to close this once after releasing the fix. Else team might miss the issue.

to which I agree specially because we don't have a fast release cycle so that it's easier to see an open bug exist (avoiding duplicates before we release) and the label makes it easy to filter by label and close whatever released, once released.

Happy to discuss this or formalize it once we have a workflow page to look at +1

**Comment by Po-code** [comment]
sorry for popping in randomly with an "unrelated" statement. 

"YOU GUYS/GALS/UNDISCLOSED ROCK"

**Comment by fpliger** [comment]
@Po-code TY so much for the kind words!! So much appreciated!! ❤️

**Comment by Po-code** [comment]
Well met friend! But It is i that thanks you. Im not much of a contributer
to the open source  (publicly anyways) as a result..my github profile hasnt
earned badges and the repo isnt populated with any
software/libraries/packages that I have built or hacked together lol..
Anyways if you want to know more about some of things I built or feel like
maybe even incorporating some of them into some of your or your teams
projects. Dont hesitate to let me know and ill gladly send you the works
with hopes of feedback or some advice/pointers.

**Comment by WebReflection** [comment]
I believe this got released by this time :sweat_smile:

**Comment by WebReflection** [comment]
> Hello again. Cant believe half a year has gone by since my previous comment.

apologies we've been busy "*changing the world*" but it's still our duty to go through the backlog and close "*the closable*", I hope you can forgive us for the wait.

> Anyways my statement still stands

There is no XSS attack vector in current release and nothing in here is a vector for XSS so your statement should be reconsidered? If you can provide any XSS that shows something undesired and that's not already part of the HTML / W3C standard, we'd be happy to fix it ASAP too.

So far, that example was not presented or not valid with our current offer.

**Comment by Po-code** [comment]
> > Hello again. Cant believe half a year has gone by since my previous comment.
> 
> apologies we've been busy "_changing the world_" but it's still our duty to go through the backlog and close "_the closable_", I hope you can forgive us for the wait.
> 
> > Anyways my statement still stands
> 
> There is no XSS attack vector in current release and nothing in here is a vector for XSS so your statement should be reconsidered? If you can provide any XSS that shows something undesired and that's not already part of the HTML / W3C standard, we'd be happy to fix it ASAP too.
> 
> So far, that example was not presented or not valid with our current offer.

im sorry let me clear this up for you, I never was apart of the XSS subject of this conversation I only left a comment that was unrelated to the topic, that is what I meant when I said "statement", as in, from my previous comment 6 months ago. I posted this as a renewal of my compliment for/to/of the py-script team/collab devs. And Why? because I got an email notification that that linked me to here. Hope this helps.
