### ISSUE TITLE
[EPIC] Better Visual Components Proposal 

### ISSUE THREAD

**Issue by fpliger** [pyscript/pyscript#447]
This is an umbrella issue to collect the tasks needed to re-design a more solid and flexible presentation design for all the visual components:

* [ ] [Replace Tailwind with a pure CSS solution ](https://github.com/pyscript/pyscript/issues/446)
* [ ] Propose a design that allows dynamic theming of the visual elements. Ideally, this could/should be a non PyScript specific design that can play well in supporting translation between PyScript and other frameworks that generate UI (i.e., Toga?). This discussion can eventually be part of the discussions in #340 
* [ ] [Implement dynamic CSS and theming support](https://github.com/pyscript/pyscript/issues/340)

**Comment by freakboy3742** [comment]
There isn't really an opportunity to "share themes" with Toga - but the reason why may be illustrative for PyScript's theming approach.

Toga deliberately *does not* support themes - the core look and feel of an app is entirely determined by the platform. On iOS, buttons don't have borders, and match the background color; on macOS, they're gray, and have a slightly rounded borders; and so on. This is very deliberately *not* opened to the end user to control; if you don't like the look and feel of the widgets on your platform, take that up with your operating system vendor, or pick a different platform :-)

Toga *does* have the ability to modify the appearance of some widgets for "functional" purposes - e.g., you can say "I want this button to be red, because it's an Emergency stop" button. The mechanism it uses to do that is effectively CSS (technically, it's a CSS-like language subset called Pack, but the long game is to use an actual CSS implementation). This means you end up writing code like:

     toga.Button("Emergency Stop", style=Pack(background_color='red'))

You *can't* change the fundamental appearance of a button/selection/table though. The only stylistic elements that are exposed are relatively simple color/background/font styles, and are very explicitly exposed on a per-widget basis; just because you define a color style on a widget, doesn't mean the color will change - either because the widget or the platform defines that the color isn't user-modifiable.

IMHO, there is a analog to what PyScript could/should aim for. The web doesn't have a consistent look and feel for apps - but PyScript is in a position to provide a single stylesheet that defines the "PyScript look and feel". That appearance won't be to everyone's taste, but you can stake out what a PyScript looks like by default.

There are then 2 distinct modes of extension:
1. *Specific* style elements can be exposed on *specific* widgets, such as the background color of a button. This could be in the down with specific widget attributes (e.g., `<py-button background-color='red'>`), or by using  CSS styles (i.e., `<py-button style="background-color: red">`) and defining how the CSS styles will be mapped to the DOM elements that actually render the button. Not all CSS styles would be automatically recognised on widgets.
2. The overall requirements of a PyScript "theme" can be documented, so others could replace (or augment) the default PyScript theme with a custom theme. This would effectively mean documenting the internals of how each widget is rendered (and maybe providing a testbed) so that theme writers can easily apply whatever stylistic approach they want.

(1) is what Toga provides on a per-widget basis. To my mind, this part isn't "theming" - its defining functional requirements of a specific widget in the context of an app. 

Implementing (2) in Toga isn't possible, because it would mean overriding the default platform look and feel; but PyScript doesn't have that constraint because of the lack of a "default" look and feel for the web. 

Another, partially related area where there is potential overlap with Toga is in establishing consistent terminology. If we agree that a "thing you click on to make an action happen" is called a "Button", it has an "on_press" handler that is triggered when it is pressed, and exposes the background color as something that can be customised, then the APIs exposed by Toga and PyScript will be very similar, and the cognitive overhead of turning a GUI written in PyScript into a native app with Toga will be lower.

**Comment by fpliger** [comment]
@MarcSkovMadsen thanks. Great point. 

Tailwind was an experiment to have something "quick and dirty"... but yeah, PyScript should be less invasive.
