### ISSUE TITLE
Proposal for better Output and Rendering Design

### ISSUE THREAD

**Issue by fpliger** [pyscript/pyscript#622]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other feature requests and couldn't find a duplicate (including also the ``type-feature`` tag)
- [X] I confirmed that it's not related to another project area (see the above section)

### What is the idea?

We need a strong[er] Design for our overall output and rendering API and application flow. "Traditional" python application happen in a console, where the medium for both is the console. PyScript is to be considered a GUI Application where, in most cases, the place for output vs display is different.

### Why is this needed

Our current design is confusing and not user friendly. Some of the reasons are that:

* it doesn't separate the concept of output from display. `output` mixes both and, while allows to explicitly write to both separately (by outputting to console and using `write` to write to DOM)
* the default behaviour is confusing
* options to customize are not enough
* documentation is bad or missing

### What should happen?

- `print`
  - Should escape (by default)
  - Is not intended for rich outputs (e.g. __repr_svg__)
  - By default you print to JS console
  - In debug mode we have a nice console that is visible by default
- `render`/`display` function
  - Intended for rich output like IPython global display
  - Probably also escapes strings
  - By default renders in-place but can also have a target (and can be overridden by output attribute on py-script tag)
No consensus on default <py-script> tag last line output behavior

**Comment by JeffersGlass** [comment]
I'm going to go out on an limb here and propose a change: 

- by default, print() outputs to the js console _**and to the page**_

I'm prosing this as an improvement for those coming to PyScript for the first time, for whom the first question might be: _"If I have a working Python script, what do I need to do to use it in py-script?"_

Currently the answer is (à la the [Try PyScript](https://github.com/pyscript/pyscript#try-pyscript) section that leads the GitHub page):

1. Copy your code into a `.html` file
2. Surround it with `<py-script>` and `</py-script>`
3. Copy this magic bit of text into the file as well: `<link rel="stylesheet" href="https://pyscript.net/latest/pyscript.js" />`
4. Open the file in a browser

And, since print (and writes to stdout) display on the page by default, in this scenario what the user sees in their browser sees is a decent approximation* of what they'd see when run their script in a terminal. I think this is a key _"Oh that's cool! It just works!"_ moment for new PyScript users.

If print()/writes to stdout only go to the js console by default, the user opens the page to see... a blank page. Adding the a step (5) above (_"Open the development console"_) is easy enough, but what the budding Pyscriptster sees there doesn't look much like what they're used to seeing in the terminal - and especially with the amount of logging when Pyodide/PyScript load, it's pretty intimidating.

That said, I think there should be a simple way to disable this functionality. Perhaps a global function that users can call, or perhaps in `<py-config>`; something that tells stdout to not display on the page, and only appear in the js console. This would be something users would learn about fairly early in their PyScript learning process, and especially if it's global/centralized, it's not much of a burden once you're more familiar with the framework.

I think that little bit of extra burden on experienced PyScript users is worth the positivity of the first user experience, in which `print("Hello, world")` just works.

---

*Of course there's lots of ways that any arbitrary Python script can fail to work in the browser/pyodide/pyscript, but at least the user gets an exception printed to the page. And solving issues that raise exceptions is a familiar task for Python programmers, where interpreting the js console isn't.

**Comment by marimeireles** [comment]
In general I agree with @JeffersGlass input.
I think Fabio and I discussed this earlier but didn't really arrive to any conclusion.
Do you think it's an ok behavior to having it print by default both on the web and on the console, @fpliger?

**Comment by fpliger** [comment]
@JeffersGlass @marimeireles that's a fair point.. 

The core of the issue is on the fact that `print/output` != `display`. Basically, the former is a way to print statements somewhere for multiple reasons while the latter is an explicit way to display things in my UI. The core of the problem here is that there are multiple flows of how a user might think they PyScript App/Script.  Do they intend to use it as a console-like app? A notebook/exploration workflow? A visual application with a UI? It's really hard to allow users "to do the right thing" if we don't provide them finer grain controls... and that's the reason the proposal introduces the new higher-level `display` function.

We could provide options to support these many cases but, ultimately, I think we'll have to try/fix/try/fix a few times before we get what are the right defaults here.

**Comment by JeffersGlass** [comment]
@fpliger Absolutely agree with you - having a `display` function that provides ways to shape the way that content is created and deliver it to the right place in the window/DOM is much superior to relying on `print`/stdout to handle everything. And that instructing PyScript users to use 'display` whenever they way something output to the screen itself is probably the way to go. 

I was just advocating for the boring old `print` statement to, by default, also output to somewhere visible in the browser window, so the "I copied some Python code from the internet into a \<py-script\> tag" situation at least produces some on-screen output. And that that option could be disabled by configuration. But maybe that's harming the overall design of the setup in favor of a specific new-user case.

**Comment by fpliger** [comment]
@JeffersGlass  yeah, I get your point. I actually do agree that there are cases for `print` (`log`, etc..) outputting to an element on the DOM [**but(!)** probably not by default]... Other core devs actually prefer a clear cut and not allow it at all. I think this is the type of thing that we'll have to tune in time.

**Comment by astrojuanlu** [comment]
To add another data point, as a newcomer I actually expected `print` to be sort of equivalent to `console.log`. Seeing the output in the DOM was kind of weird.

**Comment by antocuni** [comment]
Sorry, chiming in late in the conversation.
I agree with Fabio that there are many different use cases and workflows and we should find a way to accommodate all of them.
On the other hand, I also agree with @JeffersGlass that "good old boring scripts using `print`" should work more or less out of the box.

I think the key of the solution is already in @fpliger's original message, although it was probably overlooked:
> In debug mode we have a nice console that is visible by default

Let me explain more in detail and try to reconcile the various positions. This is my proposal:

1. we introduce the concept of the `pyscript terminal`: this is an HTML element which  can display `stdout` and `stderr`
2. by default, emscripten's `stdout` and `stderr` are printed *both* to `console.log` and to the `pyscript terminal`. Bonus point: you don't have to do anything special to python's `print()` because it automatically prints to `stdout`.
3. the `pyscript terminal` can be in three states:
    - *visible*: it's clearly visible in the page (e.g., docked on the bottom or on the right)
    - *minimized*: it's not visible, but we put an icon in some corner which makes it visible when clicked
    - *auto*: starts minimized, but automatically opens as soon as you do the first `print()`
    - *hidden*: not visible at all (possible optimization: when the terminal it's hidden, we don't even capture/save the output)
4. the `pyscript terminal` can be useful for more than just displaying output. E.g., I can imagine to have a way to use `pdb` in it.

The initial state of the terminal is configurable with `<py-config>` depending on your needs:
- beginners learning how to program probably want it to be visible; this makes it easy e.g. to use `print()` as a debugging tool
- "hackable apps", "exploratory notebooks", "debug mode apps" etc. probably wants it to be minimized: by default it's not needed, but it can be easily accessed if you want
- "production ready professional apps" want to make it hidden

What is the best default state? I guess it should be "auto", so that you automatically get a terminal if you use `print()`, but don't get it in your way if you don't.

**Comment by marimeireles** [comment]
Relevant to the discussion as in we should keep in mind: https://github.com/pyscript/pyscript/issues/276
